merchex/listings/urls.py
from django.conf.urls import handler404
from django.urls import path
from . import views

handler404 = 'listings.views.custom_404_view'

urlpatterns = [
    path('email-sent/', views.email_sent, name='email-sent'),
    path('bands/add/', views.band_create, name='band-create'),
]

merchex/merchex/urls.py
from os import name
from django.contrib import admin
from django.urls import path
from listings import views 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bands/', views.band_list, name='band-list'),
    path('bands/<int:id>/', views.band_detail, name='band-detail'),
    path('bands/add/', views.band_create, name='band-create'),
    path('about/', views.about),
    path('listing/', views.listing, name='listing'),
    path('contact/', views.contact),
    path('listing/<int:id>/', views.listing_detail, name='listing-detail'),
    path('listing/add/', views.listing_create, name='listing-create'),
    path('contact/', views.contact, name='contact'),
    path('email-sent/', views.email_sent, name='email-sent'),

]

merchex/urls.py
from django.conf.urls import handler404
from django.urls import path
from . import views

urlpatterns = [
    # ...existing code...
    path('bands/<int:id>/', views.band_detail, name='band-detail'),
    # ...existing code...
]

handler404 = 'merchex.views.custom_404_view'

merchex/listings/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator

class Band(models.Model):
    class Genre(models.TextChoices):
        HIP_HOP = 'HH'
        SYNT_POP = 'SP'
        ALTERNATIVE_ROCK = 'AR'
    name = models.CharField(max_length=100)
    genre = models.fields.CharField(choices=Genre.choices, max_length=5)
    biography = models.fields.CharField(max_length=1000)
    year_formed = models.fields.IntegerField(validators=[MinValueValidator(1900),MaxValueValidator(2024)])
    active = models.fields.BooleanField(default=True)
    official_website = models.fields.URLField(null=True, blank=True)
    
    def __str__(self):
        return self.name
    
class Listing(models.Model):
    class ListingType(models.TextChoices):
        ALBUM = 'AL'
        SINGLE = 'SI'
        EP = 'EP'
        COMPILATION = 'CO'
    name = models.fields.CharField(max_length=100)
    description = models.fields.CharField(max_length=1000)
    sold = models.fields.BooleanField(default=False)
    year = models.fields.IntegerField(validators=[MinValueValidator(1900),MaxValueValidator(2024)])
    type = models.fields.CharField(choices=ListingType.choices, max_length=5)
    def __str__(self):
        return self.name
    band = models.ForeignKey(Band, null=True, on_delete=models.SET_NULL)
    

merchex/listings/views.py
from django.http import HttpResponse
from django.shortcuts import render
from listings.models import Band, Listing
from listings.form import ContactUsForm, BandForm, ListingForm
from django.core.mail import send_mail
from django.shortcuts import redirect

def band_list(request):
    bands = Band.objects.all()
    return render(request, 'listings/band_list.html', context={'bands': bands})

def band_detail(request, id):
    band = Band.objects.get(id=id)
    return render(request, 'listings/band_detail.html', context={'band': band})

def about(request):
    return HttpResponse('<h1>A propos</h1> <p>Je suis un paragraph test</p>')

def listing(request):
    listings = Listing.objects.all()
    return render(request, 'listings/listing.html', context={'listings': listings})

def listing_detail(request, id):
    listing = Listing.objects.get(id=id)
    return render(request, 'listings/listing_detail.html', context={'listing': listing})

def contact(request):
    return render(request, 'listings/contact.html', context={})

def contact(request):
    form = ContactUsForm()
    if request.method == 'POST':
        form = ContactUsForm(request.POST)
        if form.is_valid():
            send_mail(subject=f'Message from {form.cleaned_data["name"] or "anonyme"} via MerchEx contact Us Form',
            message=form.cleaned_data['message'],
            from_email=form.cleaned_data['email'],
            recipient_list=['admin@merchex.xyz'],
            )
        return redirect('email-sent')
            
    else:
        form = ContactUsForm()
    return render(request, 'listings/contact.html', context={'form': form})

def band_create(request):
    if request.method == 'POST':
        form = BandForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('band-list')
    else:
        form = BandForm()
    return render(request, 'listings/band_create.html', {'form': form})

def listing_create(request):
    if request.method == 'POST':
        form = ListingForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('listing')
    else:
        form = ListingForm()
    return render(request, 'listings/listing_create.html', {'form': form})
    

def email_sent(request):
    return render(request, 'listings/email_sent.html')

merchex/views.py
from django.shortcuts import render

def custom_404_view(request, exception):
    return render(request, '404.html', status=404)

merchex/listings/templates/listings/band_create.html
{% extends "listings/base.html" %} {% block content %}
<h2>Je suis la page de création de groupe</h2>

<form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Envoyer">
</form>

{% endblock %}

merchex/listings/templates/listings/band_detail.html
{% extends 'listings/base.html' %}

{% block content %}

<h2>{{ band.name }}</h2>

<ul>
 <li>Genre : {{ band.get_genre_display }}</li>
 <li>Année de formation : {{ band.year_formed }}</li>
 <li>Actif : {{ band.active|yesno }}</li>
 {% if band.official_website %}
 <li><a href="{{ band.official_website }}">{{ band.official_website }}</a></li>
    {% endif %}
</ul>

<p>{{ band.biography }}</p>
<a href="{% url 'band-list' %}">Retour à la liste des groupes</a>

{% endblock %}

merchex/listings/templates/listings/band_list.html
{% extends "listings/base.html" %} 
{% block content %}
<h1>Hello Django !</h1>
 <a href="{% url 'band-create' %}">Créer un groupe</a>
<ul>
  {% for band in bands %}
  <li><a href="{% url 'band-detail' band.id %}">{{ band.name }}</a></li>
  {% endfor %}
</ul>

{% endblock %}

merchex/listings/templates/listings/base.html
{% load static %}
<html>
  <head>
    <link rel="stylesheet" href="{% static 'listings/styles.css' %}" />
    <title>Coucou</title>
  </head>
  <body>
     <nav>
      <a href="{% url 'band-list' %}">Groupes</a>
      <a href="{% url 'listing' %}">Listings</a>
      <a href="{% url 'contact' %}">Contact</a>
     </nav>

    {% block content %}{% endblock %}
  </body>
</html>

merchex/listings/templates/listings/contact.html
{% extends "listings/base.html" %} {% block content %}
<h2>Je suis la page contact</h2>
…
<p>Nous sommes là pour vous aider.</p>

<form action="" method="post">
{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="Envoyer">
</form>

{% endblock %}

merchex/listings/templates/listings/email_sent.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>Email envoyé</title>
</head>
<body>
    <h1>Email envoyé</h1>
    <p>Votre message a été envoyé avec succès. Nous vous répondrons dès que possible.</p>
    <a href="{% url 'contact' %}">Retour au formulaire de contact</a>
</body>
</html>

merchex/listings/templates/listings/listing.html
{% extends "listings/base.html" %} {% block content %}
<h1>Je suis la page listing</h1>
<a href="{% url 'listing-create' %}">Créer un groupe</a>
<ul>
  {% for listing in listings %}
  <li><a href="{% url 'listing-detail' listing.id %}">{{ listing.name }}</a></li>
  {% endfor %}
</ul>
{% endblock %}

merchex/listings/templates/listings/listing_create.html
{% extends "listings/base.html" %} {% block content %}
<h2>Je suis la page de création de groupe</h2>

<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Envoyer">
</form>

{% endblock %}

merchex/listings/templates/listings/listing_detail.html
{% extends 'listings/base.html' %}

{% block content %}

<h2>{{ listing.name }}</h2>

<ul>
 <li>Description : {{ listing.description }}</li>
 <li>Année de formation : {{ listing.year }}</li>
 <li>Solde : {{ sold.active|yesno }}</li>
 <li>Type : {{ listing.get_type_display }}</li>
 
 <li>Band : {{ listing.band }}</li>
 
</ul>

<p>{{ band.biography }}</p>
<a href="{% url 'listing' %}">Retour à la liste des groupes</a>

{% endblock %}